# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f958ca3932b989e9fe47c126084b53695f2f3bf1702a619019f8b876f72df5c7340649b3133c4387d3d7f7b165738febe0eb8781c131389e5539c270ab2619

test:
  secret_key_base: f6bf51a021436fd4f672bbd54fea58ac163c6f18df015a5acd65b360827ac9a05a7572eae340d52a2c4520c825296c7886937913cf6514374c42e86d8cc5a85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
